language: cpp

git:
  submodules: false

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq liblapack-dev libarpack2-dev libblas-dev libconfig++-dev
   - git submodule update --init --recursive

before_script: 
  - ./setup.sh

script: 
  - make -j 1

compiler: 
  - gcc
