language: cpp

git:
  submodules: false

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq liblapack-dev libarpack2-dev libblas-dev

before_script: 
  - ./setup.sh

script: 
  - make

compiler: 
  - gcc
